# 应用名称
spring:
  datasource:
    url: jdbc:mysql://114.215.175.196:33306/kai?useUnicode=true&characterEncoding=UTF-8&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
    username: root
    password: Aliyun_lysss_0

translate:
  baidu:
    app-id: "20201226000656556"
    secret-key: WLSNxrsk5QiZLRzitfX_
    url: http://api.fanyi.baidu.com/api/trans/vip/translate