# 应用名称
spring:
  datasource:
    url: jdbc:mysql://localhost:33306/kai?useUnicode=true&characterEncoding=UTF-8&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: "#jo=2p4zpK+e"

translate:
  baidu:
    app-id: "20201226000656556"
    secret-key: WLSNxrsk5QiZLRzitfX_
    url: http://api.fanyi.baidu.com/api/trans/vip/translate