# 应用名称
spring:
  application:
    name: kai-api
  datasource:
    maxActive: 10
    ###############oracle################
    url: jdbc:mysql://localhost:3306/kai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "0203"
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations:
      - classpath:/static/
translate:
  baidu:
    app-id: "20201226000656556"
    secret-key: WLSNxrsk5QiZLRzitfX_
    url: http://api.fanyi.baidu.com/api/trans/vip/translate


# 应用服务 WEB 访问端口
server:
  port: 8080
# THYMELEAF (ThymeleafAutoConfiguration)
spring.thymeleaf:
  # 开启模板缓存（默认值： true ）
  cache: true
  # 检查模板是否存在，然后再呈现
  check-template: true
  # 检查模板位置是否正确（默认值 :true ）
  check-template-location: true
  #Content-Type 的值（默认值： text/html ）
  content-type : text/html
  # 开启 MVC Thymeleaf 视图解析（默认值： true ）
  enabled : true
  # 模板编码
  encoding : UTF-8
  # 要被排除在解析之外的视图名称列表，⽤逗号分隔
  excluded-view-names :
  # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
  mode : HTML5
  # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
  prefix : classpath:/templates/
  # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
  suffix : .html
